Fix minor Python syntax errors
The installation fails because of these:

	TabError: inconsistent use of tabs and spaces in indentation
	SyntaxError: Missing parentheses in call to 'print'