Fix use of deleted function
Compilation fails due to implicit cast to QChar

Compilation on void linux (qt 5.15.3+20210429) fails with
csync_exclude.cpp:489:34: error: use of deleted function 'QCharRef& QCharRef::operator=(char)'